$(document).ready(function(){
    $('.food-slider').slick({
        autoplay:true,
        slidesToShow:3,
        sliesToScroll:1,
        prevArrow:".prev-btn",
        nextArrow:".next-btn",
    })
})